# Generated by Django 4.0.4 on 2022-06-27 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('IdCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('NombreCategoria', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='chaza',
            fields=[
                ('IdChaza', models.AutoField(primary_key=True, serialize=False)),
                ('NombreChaza', models.CharField(max_length=40, verbose_name='Nombre Chaza')),
                ('Puntuacion', models.FloatField()),
                ('Descripcion', models.TextField(verbose_name='Descripción')),
                ('slug', models.SlugField(default='default', max_length=255, unique=True)),
                ('IdCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.categoria', verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='comensales',
            fields=[
                ('IdComensal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('NombreUsuario', models.CharField(default='Superusuario', max_length=20, verbose_name='Nombre a Mostrar')),
                ('RegistroFinal', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='tipoUsuario',
            fields=[
                ('IdTipoUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('NombreTipoUsuario', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicaciones',
            fields=[
                ('IdUbicacion', models.AutoField(primary_key=True, serialize=False)),
                ('NombreUbicacion', models.CharField(max_length=100, verbose_name='Ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='DuenoChaza',
            fields=[
                ('IdDuenoChaza', models.AutoField(primary_key=True, serialize=False)),
                ('IdChaza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.chaza')),
                ('IdComensal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.comensales')),
            ],
        ),
        migrations.CreateModel(
            name='comentarios',
            fields=[
                ('IdComentario', models.AutoField(primary_key=True, serialize=False)),
                ('DescripcionComentario', models.TextField(max_length=400, verbose_name='Escribe tu reseña')),
                ('PuntuacionDada', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, verbose_name='Puntuación')),
                ('IdChaza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.chaza', verbose_name='Nombre de la chaza')),
                ('IdComensal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.comensales')),
            ],
        ),
        migrations.AddField(
            model_name='comensales',
            name='IdTipoUsuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.tipousuario', verbose_name='Tipo de Usuario'),
        ),
        migrations.AddField(
            model_name='chaza',
            name='IdUbicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ubicaciones', verbose_name='Ubicación'),
        ),
    ]
