# Generated by Django 4.0.4 on 2022-06-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaza',
            name='CoordenadaX',
            field=models.CharField(blank=True, default='450px', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='chaza',
            name='CoordenadaY',
            field=models.CharField(blank=True, default='450px', max_length=6, null=True),
        ),
    ]
